### ISSUE TITLE
Django 2.0 warning

### ISSUE THREAD

**Issue by jleclanche** [django-polymorphic/django-polymorphic#292]
I figure it's best raise this early.

After #289, we get the following warning on Django 1.11:

> `if not opts.managers or cls._requires_legacy_default_manager():`
> /home/adys/src/django/django-polymorphic/.tox/py27-django111/lib/python2.7/site-packages/django/db/models/base.py:363: RemovedInDjango20Warning: Managers from concrete parents will soon qualify as default managers. As a result, the 'objects' manager won't be created (or recreated) automatically anymore on 'polymorphic.MgrInheritC' and 'mgrB' declared on 'polymorphic.MgrInheritB' will be promoted to default manager. You can declare explicitly `objects = models.Manager()` on 'MgrInheritC' to keep things the way they are or you can switch to the new behavior right away by setting `Meta.manager_inheritance_from_future` to `True`.

**Comment by meshy** [comment]
I wonder if this will fix https://github.com/django-polymorphic/django-polymorphic/issues/305?...

**Comment by brianmay** [comment]
I am getting a slightly different warning, maybe because we have overridden `objects`. I am a bit unclear about the relationship between `base_objects` and `objects`.

```
RemovedInDjango20Warning: Managers from concrete parents will soon qualify as default managers if they appear before any other managers in the MRO. As a result, 'base_objects' declared on 'polymorphic.PolymorphicModel' will no longer be the default manager for 'XYZ' in favor of 'objects' declared on 'rigs.Rig'. You can redeclare 'base_objects' on 'XYZ' to keep things the way they are or you can switch to the new behavior right away by setting `Meta.manager_inheritance_from_future` to `True`.
```

I suspect however this is something that can't be solved in django-polymorphic, however, it would be good if the documentation could be updated to reflect what we should be doing.

**Comment by brianmay** [comment]
Perhaps worth noting that Django 2.0 has been released now...

**Comment by vdboor** [comment]
djando-polymorphic 2.0 has been released with Django 2.0 support. This this issue still happen there?

**Comment by brianmay** [comment]
As far as I can tell, looks like this is fixed. Thanks.
